// <auto-generated />
using System;
using Koala.Portal.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Koala.Portal.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240401073109_003")]
    partial class _003
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Koala.Portal.Core.Models.Agenda", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AgendaTypeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CancelDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CancelDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CancelUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ComplateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ComplatedDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirmOid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCanceled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsComplated")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoteForCustomer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TicketOid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AgendaTypeId");

                    b.ToTable("Agenda");
                });

            modelBuilder.Entity("Koala.Portal.Core.Models.AgendaFirmOfficials", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AgendaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AgendaId");

                    b.ToTable("AgendaFirmOfficials");
                });

            modelBuilder.Entity("Koala.Portal.Core.Models.AgendaFixtures", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AgendaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FixtureId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("LastKm")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("StartKm")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AgendaId");

                    b.HasIndex("FixtureId");

                    b.ToTable("AgendaFixtures");
                });

            modelBuilder.Entity("Koala.Portal.Core.Models.AgendaType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BackColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BorderColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FontColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AgendaType");

                    b.HasData(
                        new
                        {
                            Id = "ce68c4e0-eff9-11ee-95d9-e848b8c82000",
                            BackColor = "#007a96",
                            BorderColor = "",
                            Description = "Müşteri veYa servisden ürün teslim alma etkinliği",
                            FontColor = "#ffffff",
                            IsActive = true,
                            Name = "Ürün Teslim Alma"
                        },
                        new
                        {
                            Id = "ce68c4e2-eff9-11ee-95d9-e848b8c82000",
                            BackColor = "#00bbdd",
                            BorderColor = "",
                            Description = "Ürün Teslimatı ",
                            FontColor = "#ffffff",
                            IsActive = true,
                            Name = "Teslimat"
                        },
                        new
                        {
                            Id = "ce68c4e4-eff9-11ee-95d9-e848b8c82000",
                            BackColor = "#c90000",
                            BorderColor = "",
                            Description = "Logo Proje Destek",
                            FontColor = "#ffffff",
                            IsActive = true,
                            Name = "Logo Proje Destek"
                        },
                        new
                        {
                            Id = "ce68c4e6-eff9-11ee-95d9-e848b8c82000",
                            BackColor = "#ff7a00",
                            BorderColor = "",
                            Description = "Müşteri Taleplerine Göre Yapılacak Proje, Uyarlama veya Geliştirmeler Hakkında Toplantı",
                            FontColor = "#ffffff",
                            IsActive = true,
                            Name = "Proje Toplantısı"
                        },
                        new
                        {
                            Id = "ce68c4e8-eff9-11ee-95d9-e848b8c82000",
                            BackColor = "#ffee98",
                            BorderColor = "",
                            Description = "Donanım Yerinde Destek",
                            FontColor = "#03347d",
                            IsActive = true,
                            Name = "Donanım Yerinde Destek"
                        },
                        new
                        {
                            Id = "ce68c4ea-eff9-11ee-95d9-e848b8c82000",
                            BackColor = "Logo Müşteri Ziyareti",
                            BorderColor = "#ffffff",
                            Description = "",
                            FontColor = "#669600",
                            IsActive = true,
                            Name = "Logo Müşteri Ziyareti"
                        },
                        new
                        {
                            Id = "ce68c4ec-eff9-11ee-95d9-e848b8c82000",
                            BackColor = "#7d0078",
                            BorderColor = "",
                            Description = "Logo dönem veya yıl sonu devir işlemleri",
                            FontColor = "#ffffff",
                            IsActive = true,
                            Name = "Logo Devir"
                        },
                        new
                        {
                            Id = "ce68c4ee-eff9-11ee-95d9-e848b8c82000",
                            BackColor = "#002585",
                            BorderColor = "",
                            Description = "Logo Yerinde Destek",
                            FontColor = "#faff00",
                            IsActive = true,
                            Name = "Logo Yerinde Destek"
                        },
                        new
                        {
                            Id = "ce68c4f0-eff9-11ee-95d9-e848b8c82000",
                            BackColor = "#ffc700",
                            BorderColor = "",
                            Description = "Personel Senelik İzin ",
                            FontColor = "#000000",
                            IsActive = true,
                            Name = "Yıllık İzin"
                        });
                });

            modelBuilder.Entity("Koala.Portal.Core.Models.AgendaUsers", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AgendaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AgendaId");

                    b.HasIndex("UserId");

                    b.ToTable("AgendaUsers");
                });

            modelBuilder.Entity("Koala.Portal.Core.Models.AppRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Koala.Portal.Core.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Lastname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Oid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Koala.Portal.Core.Models.AppUserCrmDepartment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DepartmanId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("DepartmanId");

                    b.ToTable("AppUserCrmDepartment");
                });

            modelBuilder.Entity("Koala.Portal.Core.Models.ApplicationLicences", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApplicationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApplicationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApprovedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CpuId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LicenceCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainboardId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("ApprovedByUserId");

                    b.ToTable("ApplicationLicences");
                });

            modelBuilder.Entity("Koala.Portal.Core.Models.Applications", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AppId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicationSecretKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxUserCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("Koala.Portal.Core.Models.Claims", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModuleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("Koala.Portal.Core.Models.CrmDepartment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AppDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CrmName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CrmDepartment");
                });

            modelBuilder.Entity("Koala.Portal.Core.Models.CrmFirm", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("InUse")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Oid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.ToTable("CrmFirm");
                });

            modelBuilder.Entity("Koala.Portal.Core.Models.CrmFirmContact", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirmId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("InUse")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SupportTicket")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("FirmId");

                    b.ToTable("CrmFirmContact");
                });

            modelBuilder.Entity("Koala.Portal.Core.Models.CrmPhoneNumber", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AreaCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Extension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelatedContact")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RelatedFirm")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RelatedContact");

                    b.HasIndex("RelatedFirm");

                    b.ToTable("CrmPhoneNumber");
                });

            modelBuilder.Entity("Koala.Portal.Core.Models.EmailTemplate", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("EmailTemplate");
                });

            modelBuilder.Entity("Koala.Portal.Core.Models.Fixture", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVehicle")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Fixture");

                    b.HasData(
                        new
                        {
                            Id = "ce68c4f2-eff9-11ee-95d9-e848b8c82000",
                            Description = "34-BIG-293",
                            IsActive = true,
                            IsVehicle = true,
                            Name = "Fiat Egea"
                        },
                        new
                        {
                            Id = "ce68c4f4-eff9-11ee-95d9-e848b8c82000",
                            Description = "34-FR-4680",
                            IsActive = true,
                            IsVehicle = true,
                            Name = "Volkswagen - Cady"
                        },
                        new
                        {
                            Id = "ce68c4f6-eff9-11ee-95d9-e848b8c82000",
                            Description = "Logo Departman Notebook",
                            IsActive = true,
                            IsVehicle = false,
                            Name = "Logo Notebook"
                        },
                        new
                        {
                            Id = "ce68c4f8-eff9-11ee-95d9-e848b8c82000",
                            Description = "Teknik Departman Notebook",
                            IsActive = true,
                            IsVehicle = false,
                            Name = "Teknik Notebook"
                        },
                        new
                        {
                            Id = "ce68c4fa-eff9-11ee-95d9-e848b8c82000",
                            Description = "34-FC-1504",
                            IsActive = true,
                            IsVehicle = true,
                            Name = "Fiat Punto"
                        });
                });

            modelBuilder.Entity("Koala.Portal.Core.Models.GeneratedIds", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Digit")
                        .HasColumnType("int");

                    b.Property<int>("LastNumber")
                        .HasColumnType("int");

                    b.Property<string>("ModuleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StartNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.ToTable("GeneratedIds");
                });

            modelBuilder.Entity("Koala.Portal.Core.Models.HelpDeskCatagory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HelpDeskCatogory");
                });

            modelBuilder.Entity("Koala.Portal.Core.Models.HelpDeskProblem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Views")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("HelpDeskProblem");
                });

            modelBuilder.Entity("Koala.Portal.Core.Models.HelpDeskSolution", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CustomerCanSee")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisLike")
                        .HasColumnType("int");

                    b.Property<string>("HelpDeskProblemId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Like")
                        .HasColumnType("int");

                    b.Property<string>("SolitionNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HelpDeskProblemId");

                    b.ToTable("HelpDeskSolition");
                });

            modelBuilder.Entity("Koala.Portal.Core.Models.Module", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Module");

                    b.HasData(
                        new
                        {
                            Id = "ce68c4fb-eff9-11ee-95d9-e848b8c82000",
                            Description = "Sistem bilgisayar proje yönetim uygulaması.",
                            Name = "Proje",
                            Status = 1
                        },
                        new
                        {
                            Id = "ce68c4fc-eff9-11ee-95d9-e848b8c82000",
                            Description = "Yardım masası uygulaması.",
                            Name = "Yardım Masası",
                            Status = 1
                        },
                        new
                        {
                            Id = "ce68c4fd-eff9-11ee-95d9-e848b8c82000",
                            Description = "Personel izin, toplantı gibi etkinliklerinin takibi amacıyla oluşturulan ajanda uygulaması.",
                            Name = "Ajanda",
                            Status = 1
                        });
                });

            modelBuilder.Entity("Koala.Portal.Core.Models.Project", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CancelDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EstimatedHour")
                        .HasColumnType("int");

                    b.Property<string>("FirmId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirmPersonId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProjectCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProjectManagerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectStatus")
                        .HasColumnType("int");

                    b.Property<int?>("ServiceHour")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FirmId");

                    b.HasIndex("FirmPersonId");

                    b.HasIndex("ProjectCode");

                    b.HasIndex("ProjectManagerId");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("Koala.Portal.Core.Models.ProjectFiles", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UrlSlug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectFiles");
                });

            modelBuilder.Entity("Koala.Portal.Core.Models.ProjectLine", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CancelDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ReportDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RowOrdwer")
                        .HasColumnType("int");

                    b.Property<int>("ServiceTime")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StateStatus")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectLine");
                });

            modelBuilder.Entity("Koala.Portal.Core.Models.ProjectLineNote", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectLineId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ReportNote")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectLineId");

                    b.ToTable("ProjectLineNote");
                });

            modelBuilder.Entity("Koala.Portal.Core.Models.ProjectLineWork", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CancelDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveredPerson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveredPersonOid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LetTimeDeduct")
                        .HasColumnType("bit");

                    b.Property<string>("LineId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("ReportDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RowOrdwer")
                        .HasColumnType("int");

                    b.Property<int>("TimeSpend")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LineId");

                    b.ToTable("ProjectLineWork");
                });

            modelBuilder.Entity("Koala.Portal.Core.Models.ProjectLineWorkSupports", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProjectLinetWorkId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SupportCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupportOid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectLinetWorkId");

                    b.ToTable("ProjectLineWorkSupports");
                });

            modelBuilder.Entity("Koala.Portal.Core.Models.ProjectPerson", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProjectLineId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProjectLineWorkId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ProjectLineId");

                    b.HasIndex("ProjectLineWorkId");

                    b.HasIndex("UserId");

                    b.ToTable("ProjectPerson");
                });

            modelBuilder.Entity("Koala.Portal.Core.Models.SupportFile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AddedByOid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AddedByType")
                        .HasColumnType("int");

                    b.Property<int>("AttachmentType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Endwith")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TicketId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlSlug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SupportFile");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Koala.Portal.Core.Models.Agenda", b =>
                {
                    b.HasOne("Koala.Portal.Core.Models.AgendaType", "AgendaType")
                        .WithMany("Agenda")
                        .HasForeignKey("AgendaTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgendaType");
                });

            modelBuilder.Entity("Koala.Portal.Core.Models.AgendaFirmOfficials", b =>
                {
                    b.HasOne("Koala.Portal.Core.Models.Agenda", "Agenda")
                        .WithMany("FirmOfficials")
                        .HasForeignKey("AgendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agenda");
                });

            modelBuilder.Entity("Koala.Portal.Core.Models.AgendaFixtures", b =>
                {
                    b.HasOne("Koala.Portal.Core.Models.Agenda", "Agenda")
                        .WithMany("AgendaFixtures")
                        .HasForeignKey("AgendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Koala.Portal.Core.Models.Fixture", "Fixture")
                        .WithMany("AgendaFixtures")
                        .HasForeignKey("FixtureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agenda");

                    b.Navigation("Fixture");
                });

            modelBuilder.Entity("Koala.Portal.Core.Models.AgendaUsers", b =>
                {
                    b.HasOne("Koala.Portal.Core.Models.Agenda", "Agenda")
                        .WithMany("Users")
                        .HasForeignKey("AgendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Koala.Portal.Core.Models.AppUser", "User")
                        .WithMany("Events")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agenda");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Koala.Portal.Core.Models.AppUserCrmDepartment", b =>
                {
                    b.HasOne("Koala.Portal.Core.Models.AppUser", "User")
                        .WithMany("UserDepartments")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Koala.Portal.Core.Models.CrmDepartment", "Department")
                        .WithMany("DepartmentUsers")
                        .HasForeignKey("DepartmanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Koala.Portal.Core.Models.ApplicationLicences", b =>
                {
                    b.HasOne("Koala.Portal.Core.Models.Applications", "Applications")
                        .WithMany("ApplicationLicences")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Koala.Portal.Core.Models.AppUser", "ApprovedByUser")
                        .WithMany("ApplicationLicences")
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Applications");

                    b.Navigation("ApprovedByUser");
                });

            modelBuilder.Entity("Koala.Portal.Core.Models.Claims", b =>
                {
                    b.HasOne("Koala.Portal.Core.Models.Module", "Module")
                        .WithMany("Claims")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("Koala.Portal.Core.Models.CrmFirmContact", b =>
                {
                    b.HasOne("Koala.Portal.Core.Models.CrmFirm", "Firm")
                        .WithMany("Contacts")
                        .HasForeignKey("FirmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Firm");
                });

            modelBuilder.Entity("Koala.Portal.Core.Models.CrmPhoneNumber", b =>
                {
                    b.HasOne("Koala.Portal.Core.Models.CrmFirmContact", "RelatedContactNavigation")
                        .WithMany("Phones")
                        .HasForeignKey("RelatedContact");

                    b.HasOne("Koala.Portal.Core.Models.CrmFirm", "RelatedFirmNavigation")
                        .WithMany("Phones")
                        .HasForeignKey("RelatedFirm");

                    b.Navigation("RelatedContactNavigation");

                    b.Navigation("RelatedFirmNavigation");
                });

            modelBuilder.Entity("Koala.Portal.Core.Models.GeneratedIds", b =>
                {
                    b.HasOne("Koala.Portal.Core.Models.Module", "Module")
                        .WithMany("GeneratedIds")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("Koala.Portal.Core.Models.HelpDeskProblem", b =>
                {
                    b.HasOne("Koala.Portal.Core.Models.HelpDeskCatagory", "Catogory")
                        .WithMany("HelpDeskProblems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catogory");
                });

            modelBuilder.Entity("Koala.Portal.Core.Models.HelpDeskSolution", b =>
                {
                    b.HasOne("Koala.Portal.Core.Models.HelpDeskProblem", "HelpDeskProblem")
                        .WithMany("HelpDeskSolitions")
                        .HasForeignKey("HelpDeskProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HelpDeskProblem");
                });

            modelBuilder.Entity("Koala.Portal.Core.Models.Project", b =>
                {
                    b.HasOne("Koala.Portal.Core.Models.CrmFirm", "Firm")
                        .WithMany("FirmProjects")
                        .HasForeignKey("FirmId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Koala.Portal.Core.Models.CrmFirmContact", "FirmPerson")
                        .WithMany("PersonProjects")
                        .HasForeignKey("FirmPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Koala.Portal.Core.Models.AppUser", "ProjectManager")
                        .WithMany("ManagedProjects")
                        .HasForeignKey("ProjectManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Firm");

                    b.Navigation("FirmPerson");

                    b.Navigation("ProjectManager");
                });

            modelBuilder.Entity("Koala.Portal.Core.Models.ProjectFiles", b =>
                {
                    b.HasOne("Koala.Portal.Core.Models.Project", "Project")
                        .WithMany("ProjectFiles")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Koala.Portal.Core.Models.ProjectLine", b =>
                {
                    b.HasOne("Koala.Portal.Core.Models.Project", "Project")
                        .WithMany("ProjectLines")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Koala.Portal.Core.Models.ProjectLineNote", b =>
                {
                    b.HasOne("Koala.Portal.Core.Models.ProjectLine", "ProjectLine")
                        .WithMany("LineNotes")
                        .HasForeignKey("ProjectLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectLine");
                });

            modelBuilder.Entity("Koala.Portal.Core.Models.ProjectLineWork", b =>
                {
                    b.HasOne("Koala.Portal.Core.Models.ProjectLine", "Line")
                        .WithMany("LineWorks")
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Line");
                });

            modelBuilder.Entity("Koala.Portal.Core.Models.ProjectLineWorkSupports", b =>
                {
                    b.HasOne("Koala.Portal.Core.Models.ProjectLineWork", "ProjectLineWork")
                        .WithMany("ReleatedSupport")
                        .HasForeignKey("ProjectLinetWorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectLineWork");
                });

            modelBuilder.Entity("Koala.Portal.Core.Models.ProjectPerson", b =>
                {
                    b.HasOne("Koala.Portal.Core.Models.Project", "Project")
                        .WithMany("ProjectPerson")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Koala.Portal.Core.Models.ProjectLine", "ProjectLine")
                        .WithMany("LinePersons")
                        .HasForeignKey("ProjectLineId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Koala.Portal.Core.Models.ProjectLineWork", "ProjectLineWork")
                        .WithMany("WorkPersons")
                        .HasForeignKey("ProjectLineWorkId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Koala.Portal.Core.Models.AppUser", "User")
                        .WithMany("WorkedProjects")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("ProjectLine");

                    b.Navigation("ProjectLineWork");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Koala.Portal.Core.Models.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Koala.Portal.Core.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Koala.Portal.Core.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Koala.Portal.Core.Models.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Koala.Portal.Core.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Koala.Portal.Core.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Koala.Portal.Core.Models.Agenda", b =>
                {
                    b.Navigation("AgendaFixtures");

                    b.Navigation("FirmOfficials");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Koala.Portal.Core.Models.AgendaType", b =>
                {
                    b.Navigation("Agenda");
                });

            modelBuilder.Entity("Koala.Portal.Core.Models.AppUser", b =>
                {
                    b.Navigation("ApplicationLicences");

                    b.Navigation("Events");

                    b.Navigation("ManagedProjects");

                    b.Navigation("UserDepartments");

                    b.Navigation("WorkedProjects");
                });

            modelBuilder.Entity("Koala.Portal.Core.Models.Applications", b =>
                {
                    b.Navigation("ApplicationLicences");
                });

            modelBuilder.Entity("Koala.Portal.Core.Models.CrmDepartment", b =>
                {
                    b.Navigation("DepartmentUsers");
                });

            modelBuilder.Entity("Koala.Portal.Core.Models.CrmFirm", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("FirmProjects");

                    b.Navigation("Phones");
                });

            modelBuilder.Entity("Koala.Portal.Core.Models.CrmFirmContact", b =>
                {
                    b.Navigation("PersonProjects");

                    b.Navigation("Phones");
                });

            modelBuilder.Entity("Koala.Portal.Core.Models.Fixture", b =>
                {
                    b.Navigation("AgendaFixtures");
                });

            modelBuilder.Entity("Koala.Portal.Core.Models.HelpDeskCatagory", b =>
                {
                    b.Navigation("HelpDeskProblems");
                });

            modelBuilder.Entity("Koala.Portal.Core.Models.HelpDeskProblem", b =>
                {
                    b.Navigation("HelpDeskSolitions");
                });

            modelBuilder.Entity("Koala.Portal.Core.Models.Module", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("GeneratedIds");
                });

            modelBuilder.Entity("Koala.Portal.Core.Models.Project", b =>
                {
                    b.Navigation("ProjectFiles");

                    b.Navigation("ProjectLines");

                    b.Navigation("ProjectPerson");
                });

            modelBuilder.Entity("Koala.Portal.Core.Models.ProjectLine", b =>
                {
                    b.Navigation("LineNotes");

                    b.Navigation("LinePersons");

                    b.Navigation("LineWorks");
                });

            modelBuilder.Entity("Koala.Portal.Core.Models.ProjectLineWork", b =>
                {
                    b.Navigation("ReleatedSupport");

                    b.Navigation("WorkPersons");
                });
#pragma warning restore 612, 618
        }
    }
}
